language: python
python:
  - "3.6"
os: linux
dist: trusty
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
before_script:
# - sudo pip install --upgrade pip
 - pip3 install -r requirements.txt
 - chmod +x run.sh
script:
- echo hello world